apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cd-pipeline-run-
spec:
  pipelineRef:
    name: cd-pipeline

  params:
    - name: repo-url
      value: https://github.com/alicess19/devops-capstone-project.git

  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
