apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
      type: string

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      runAfter:
        - cleanup
      taskRef:
        name: clone-repository
      params:
        - name: repo-url
          value: $(params.repo-url)
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: verify-files
      runAfter:
        - clone
      taskRef:
        name: verify-files
      workspaces:
        - name: source
          workspace: pipeline-workspace
